name: (check whether test/sync should trigger)

on:
  workflow_call:
    outputs:
      condition:
        description: "Whether the diff workflow should run or not"
        value: ${{ jobs.should.outputs.condition }}

jobs:
  should:                                                      # we do not want to run this on our generated PRs
    runs-on: ubuntu-latest
    outputs:
      condition: ${{ steps.condition.outputs.condition }}
    steps:
      - run: echo "HEAD -> ${{ github.head_ref }}"
      - id: condition
        run: |                                                # check if the event_name & head_ref passes our checks
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "condition=true" >> $GITHUB_OUTPUT
          else
            node -e "('${{ github.head_ref }}').indexOf('tokens-sync') === -1 ? console.log('condition=true') : console.log('condition=false')" >> $GITHUB_OUTPUT
          fi
