name: sync spectrum-tokens with tokens-studio-data
run-name: ${{ github.actor }} is syncing up some tokens! 🚀
on:
  pull_request:
    types: [closed]
    branches:
      - main                                                  # only run on PRs targetting main
    paths:
      - 'src/tokens-studio/spectrum2-colors/**'               # only run when files in this path change
  workflow_dispatch:
jobs:
  setup:                                                      # we do not want to run this on our generated PRs
    runs-on: ubuntu-latest
    outputs:
      condition: ${{ steps.condition.outputs.condition }}
    steps:
      - id: condition
        run: |                                                # check if the event_name & head_ref passes our checks
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "condition=true" >> $GITHUB_OUTPUT
          else
            node -e "('${{ github.head_ref }}').indexOf('tokens-sync') === -1 ? console.log('condition=true') : console.log('condition=false')" >> $GITHUB_OUTPUT
          fi
  diff:
    needs: [setup]
    if: ${{ needs.setup.outputs.condition == 'true' && github.event.pull_request.merged == true }}        # only run if the setup job determined this was not a generated PR
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.head_ref }} and your repository is ${{ github.repository }}."
      - name: Check out tokens-studio-data code
        uses: actions/checkout@v4
        with:
          path: spectrum-tokens-studio-data
      - name: Check out spectrum-tokens code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/spectrum-tokens
          path: spectrum-tokens
          ref: beta
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.x
      - name: Run the diff script
        run: node spectrum-tokens-studio-data/.github/workflows/diff.js -source=./spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/ -destination=./spectrum-tokens/packages/tokens/src/
      - name: Add stuff to log
        run: |
          echo >> cout.log
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> cout.log
          echo >> cout.log
          for file in ./logs/*; do echo '<details><summary>'; echo $file; echo '</summary>'; echo '<p>'; cat $file; echo; echo '</p></details>'; echo; done >> cout.log
      - name: Log the script summary
        run: |
          cat cout.log >> $GITHUB_STEP_SUMMARY
      - name: Append script summary to PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          gh pr comment ${{ github.event.number }} --body-file cout.log --repo ${{ github.repository}}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Archive change logs
        if: ${{ hashFiles('./logs/*.json') != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: changes
          path: ./logs/*.json
      - name: Create spectrum-tokens PR...
        id: cpr-spectrum-tokens
        uses: peter-evans/create-pull-request@v5
        with:
          path: spectrum-tokens
          branch: tokens-sync/patch
          title: "feat: updates from tokens-studio sync operation"
          body: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Check spectrum-tokens PR
        if: ${{ steps.cpr-spectrum-tokens.outputs.pull-request-number }}
        run: |
          echo "[Spectrum Tokens Pull Request URL](${{ steps.cpr-spectrum-tokens.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY
      - name: Create spectrum-tokens-studio-data PR...
        id: cpr-tokens-studio
        uses: peter-evans/create-pull-request@v5
        with:
          path: spectrum-tokens-studio-data
          branch: tokens-sync/patch#${{ steps.cpr-spectrum-tokens.outputs.pull-request-number }}
          title: "feat: updates from spectrum-tokens sync operation"
          body: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Check tokens-studio PR
        if: ${{ steps.cpr-tokens-studio.outputs.pull-request-number }}
        run: |
          echo "[Tokens Studio Pull Request URL](${{ steps.cpr-tokens-studio.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY
      - run: echo "🍏 This job's status is ${{ job.status }}."