name: SYNC FOUNDATIONS

on:
  workflow_dispatch

jobs:
  check_should_run:      
    uses: ./.github/workflows/_diff-should-run.yml
    secrets: inherit
  diff_do:
    needs: [check_should_run]
    if: ${{ needs.check_should_run.outputs.condition == 'true' && (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch')}}
    uses: ./.github/workflows/_diff-trigger-sync.yml
    with:
      source: foundations                         # the tokens-studio data we want to compare (folder prefix in the repo)
      branch: snapshot-s2-foundations             # the spectrum-tokens data we want to compare (branch of the repo)
    secrets: inherit