name: TEST S1

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main                                          # only run on PRs targetting main
    paths:
      - 'src/tokens-studio/spectrum-colors/**'        # only run when files in these paths change
      - 'src/tokens-studio/spectrum-non-colors/**'

jobs:
  check_should_run:      
    uses: ./.github/workflows/_diff-should-run.yml
    secrets: inherit
  diff_test:
    needs: [check_should_run]
    if: ${{ needs.check_should_run.outputs.condition == 'true' }}
    uses: ./.github/workflows/_diff-trigger-test.yml
    with:
      source: spectrum                            # the tokens-studio data we want to compare (folder prefix in the repo)
      branch: s1-legacy                           # the spectrum-tokens data we want to compare (branch of the repo)
    secrets: inherit