name: TEST S2-NON-COLORS

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main                                          # only run on PRs targetting main
    paths:
      - 'src/tokens-studio/spectrum2-non-colors/**'   # only run when files in this path change

jobs:
  check_should_run:      
    uses: ./.github/workflows/_diff-should-run.yml
    secrets: inherit
  diff_test:
    needs: [check_should_run]
    if: ${{ needs.check_should_run.outputs.condition == 'true' }}
    uses: ./.github/workflows/_diff-trigger-test.yml
    with:
      source: spectrum2-non-colors                    # the tokens-studio data we want to compare (folder in the repo)
      branch: beta                                    # the spectrum-tokens data we want to compare (branch of the repo)
    secrets: inherit